easy_admin:
    design:
        menu:
            - {label: "Mijn tabellen"}
            - label: "Fabmoments"
              children:
                    - {entity: Fabmoment, label: "Fabmoments lijst", icon: "tools"}
                    - {entity: FabFile, label: "Fabmoment files", icon: "file"}
            - {label: "Mijn gebruikers"}
            - label: "Users"
              children:
                    - {entity: User, label: "Users lijst", icon: "user-astronaut"}
                    - {entity: MachineRecht, label: "Machinerechten", icon: "tools"}
                    - {entity: MachineRecht, label: "Add Machinerecht", icon: "plus", params: {action: 'new'}}
            - Nieuws

    site_name: 'FabLab Dashboard'
    user:
        display_avatar: false
        name_property_path: 'useVn'

    entities:
    - App\Entity\User
    - App\Entity\Nieuws
    - App\Entity\FabFile
    - App\Entity\Fabmoment
    - App\Entity\MachineRecht

