easy_admin:
    design:
        menu:

            - {label: "Info"}
            - label: "Paginacontent"
              children:
                    - {entity: FablabInfo, label: "'Wat is FabLab'", icon: "info"}
                    - {entity: Regels, label: "Huisregels", icon: "gavel"}
                    - {entity: FaqCategorie, label: "FAQ Categorie", icon: "question-circle"}
                    - {entity: Faq, label: "FAQ", icon: "question"}
                    - {entity: Stage, label: "Stage", icon: "child"}
            - label: "Machines"
              children:
                    - {entity: MachineCategorie, label: "Machines Catgorie", icon: "cogs"}
                    - {entity: Machine, label: "Machines", icon: "cog"}
                    - {entity: MachineStaat, label: "Machine Staat", icon: "thermometer-half"}
                    - {entity: MachineLink, label: "Informatie Links", icon: "link"}
                    - {entity: MachineFile, label: "Opmaak Files", icon: "paperclip"}
            - label: "Shop"
              children:
                    - {entity: ShopCategorie, label: "Shop Categorie", icon: "cubes"}
                    - {entity: Shopmateriaal, label: "Shop Item", icon: "cube"}


            - {label: "Fabmoments"}
            - label: "Fabmoments"
              children:
                    - {entity: Fabmoment, label: "Fabmoments", icon: "tools"}
                    - {entity: FabImg, label: "Fabmoment Foto's", icon: "image"}
                    - {entity: FabFile, label: "Fabmoment Files", icon: "paperclip"}
                    - {entity: Materiaal, label: "Fabmoment Materialen", icon: "cube"}


            - {label: "Nieuws & Events"}
            - label: "Nieuws"
              children:
                    - {entity: Nieuws, label: "Nieuws", icon: "newspaper"}
            - label: "Events"
              children:
                    - {entity: Event, label: "Event", icon: "calendar"}
                    - {entity: Inschrijving, label: "Inschrijvingen", icon: "calendar-check"}


            - {label: "Users"}
            - label: "Users"
              children:
                    - {entity: User, label: "Users lijst", icon: "user-astronaut"}
                    - {entity: MachineRecht, label: "Machinerechten", icon: "thumbs-up"}
                    - {entity: MachineLog, label: "Machine-logs", icon: "stopwatch"}


#GLOBAL==============================================================================================================================
#==============================================================================================================================


    site_name: 'FabLab Dashboard'
    user:
        display_avatar: false
        name_property_path: 'useVn'

    formats:
      date:     'd/m/Y'
      time:     'H:i'
      datetime: 'd/m/Y H:i'

    list:
      actions:
        - { name: 'show', icon: 'eye', label: '' }
        - { name: 'edit', icon: 'pencil', label: '' }
        - { name: 'delete', icon: 'trash-alt', label: '' }



#ENTITIES==============================================================================================================================
#==============================================================================================================================

    entities:
#Info==============================================================================================================================
  #Paginacontent--------------------------------------------------------------------------------------------------------------------
      FablabInfo:
        class: App\Entity\FablabInfo
        list:
          sort: ['infoOrder', 'ASC']
          fields:
            - {property: 'infoOrder', label: 'Rangschikking'}
            - {property: 'infoSubtitel', label: 'Subtitel'}
            - {property: 'infoOmschrijving', type: 'raw', label: 'Omschrijving' }
            - updatedAt
        form:
          fields:
            - {property: 'infoSubtitel', label: 'Subtitel'}
            - {property: 'infoOmschrijving', type: 'text-editor', label: 'Omschrijving'}
            - {property: 'infoOrder', label: 'Rangschikking'}
        show:
          fields:
            - {property: 'infoSubtitel', label: 'Subtitel'}
            - {property: 'infoOmschrijving', type: 'raw', label: 'Omschrijving' }
            - {property: 'infoOrder', label: 'Rangschikking'}
      Regels:
        class: App\Entity\Regels
        list:
          sort: ['regOrder', 'ASC']
          fields:
            - {property: 'regOrder', label: 'Rangschikking'}
            - {property: 'regNaam', label: 'Regel'}
            - {property: 'regOmschrijving', type: 'raw', label: 'Omschrijving'}
            - updatedAt
        form:
          fields:
            - {property: 'regNaam', label: 'Regel'}
            - {property: 'regOmschrijving', type: 'text-editor', label: 'Omschrijving'}
            - {property: 'regOrder', label: 'Rangschikking'}
        show:
          fields:
            - {property: 'regNaam', label: 'Regel'}
            - {property: 'regOmschrijving', type: 'raw', label: 'Omschrijving'}
            - {property: 'regOrder', label: 'Rangschikking'}
      FaqCategorie:
        class: App\Entity\FaqCategorie
        list:
          sort: ['faqcatOrder', 'ASC']
          fields:
            - {property: 'faqcatOrder', label: 'Rangschikking'}
            - {property: 'faqcatNaam', label: 'Categorie naam'}
        form:
          fields:
            - {property: 'faqcatNaam', label: 'Categorie naam'}
            - {property: 'faqcatOrder', label: 'Rangschikking'}
      Faq:
        class: App\Entity\Faq
        list:
        formats:
          sort: ['faqOrder', 'ASC']
          fields:
            - {property: 'faqOrder', label: 'Rangschikking'}
            - {property: 'faqFaqcat', label: 'Categorie'}
            - {property: 'faqVraag', label: 'Vraag'}
            - {property: 'faqAntwoord', type: 'raw', label: 'Antwoord'}
            - updatedAt
        form:
          fields:
            - {property: 'faqFaqcat', label: 'Categorie'}
            - {property: 'faqVraag', label: 'Vraag'}
            - {property: 'faqAntwoord', type: 'text-editor', label: 'Antwoord'}
            - {property: 'faqOrder', label: 'Rangschikking'}
        show:
          fields:
            - {property: 'faqFaqcat', label: 'Categorie'}
            - {property: 'faqVraag', label: 'Vraag'}
            - {property: 'faqAntwoord', type: 'raw', label: 'Antwoord'}
            - {property: 'faqOrder', label: 'Rangschikking'}
      Stage:
        class: App\Entity\Stage
        list:
          sort: ['stageOrder', 'ASC']
          fields:
            - {property: 'stageOrder', label: 'Rangschikking'}
            - {property: 'stageSubtitel', label: 'Subtitel'}
            - {property: 'stageOmschrijving', label: 'Omschrijving' , type: 'raw'}
            - updatedAt
        form:
          fields:
            - {property: 'stageSubtitel', label: 'Subtitel'}
            - {property: 'stageOmschrijving', label: 'Omschrijving' ,type: 'text-editor'}
            - {property: 'stageOrder', label: 'Rangschikking'}
        show:
          fields:
            - {property: 'stageSubtitel', label: 'Subtitel'}
            - {property: 'stageOmschrijving', label: 'Omschrijving' , type: 'raw'}
            - {property: 'stageOrder', label: 'Rangschikking'}

  #Machines--------------------------------------------------------------------------------------------------------------------
      MachineCategorie:
        class: App\Entity\MachineCategorie
        list:
          fields:
            - {property: 'mcatImgPad', label: 'Afbeelding'}
            - {property: 'mcatNaam', label: 'Categorie'}
            - {property: 'mcatOmschrijving', label: 'Categorie Omschrijving'}
        form:
          fields:
            - {property: 'mcatNaam', label: 'Categorie'}
            - {property: 'mcatOmschrijving', label: 'Categorie Omschrijving'}
            - {property: 'mcatImgPad', label: 'Afbeelding'}
            - {property: 'mcatImgAlt', label: 'Afbeelding Omschrijving'}
            - {property: 'machines', label: 'Machines'}
      Machine:
        class: App\Entity\Machine
        list:
          fields:
            - {property: 'machMcat', label: 'Categorie'}
            - {property: 'machImgPad', type: 'image', label: 'Afbeelding', base_path: '%uploads_machine_images_path%'}
            - {property: 'machNaam', label: 'Naam'}
            - {property: 'machOmschrijving', label: 'Omschrijving'}
        form:
          fields:
            - {property: 'machMcat', label: 'Categorie'}
            - {property: 'machNaam', label: 'Naam'}
            - {property: 'machOmschrijving', label: 'Omschrijving'}
            - {property: 'machMat', label: 'Mogelijke Materialen'}
            - {property: 'machImgPad', label: 'Afbeelding'}
            - {property: 'machImgAlt', label: 'Afbeelding Omschrijving'}
            - {property: 'machImgFile', type: 'vich_image', label: 'Afbeelding File'}
            - {property: 'machineFiles', type: 'collection', label: 'voorbeeldfiles', type_options: {entry_type: 'App\Form\MfileFileType', by_reference: false }}
        show:
          fields:
            - {property: 'machMcat', label: 'Categorie'}
            - {property: 'machNaam', label: 'Naam'}
            - {property: 'machOmschrijving', label: 'Omschrijving'}
            - {property: 'machMat', label: 'Mogelijke Materialen'}
            - {property: 'machImgPad', type: 'image', label: 'Afbeelding', base_path: '%uploads_machine_images_path%'}
            - {property: 'machImgAlt', label: 'Afbeelding Omschrijving'}
      MachineStaat:
        class: App\Entity\MachineStaat
        list:
          fields:
            - {property: 'mstaatStatus', label: 'Status'}
            - {property: 'mstaatMach', label: 'Machine'}
            - {property: 'mstaatStart', label: 'Status Begin'}
            - {property: 'mstaatStop', label: 'Status Eind'}
        form:
          fields:
            - {property: 'mstaatStatus', label: 'Status'}
            - {property: 'mstaatMach', label: 'Machine'}
            - {property: 'mstaatStart', label: 'Status Begin'}
            - {property: 'mstaatStop', label: 'Status Eind'}
      MachineLink:
        class: App\Entity\MachineLink
        list:
          fields:
            - {property: 'mlinkMach', label: 'Machine'}
            - {property: 'mlinkTitel', label: 'link omschrijving'}
            - {property: 'mlinkPad', label: 'Url', type: 'url'}
        form:
          fields:
            - {property: 'mlinkMach', label: 'Machine'}
            - {property: 'mlinkTitel', label: 'link omschrijving'}
            - {property: 'mlinkPad', label: 'Url', type: 'url'}

      MachineFile:
        class: App\Entity\MachineFile
        list:
          fields:
            - {property: 'mfileMach', label: 'Machine'}
            - {property: 'mfileTitel', label: 'File omschrijving'}
            - {property: 'mfilePad', label: 'File', type: 'file', base_path: '%uploads_machine_file_path%'}
        form:
          fields:
            - {property: 'mfileMach', label: 'Machine'}
            - {property: 'mfileTitel', label: 'File omschrijving'}
            - {property: 'mfileFile', type: 'vich_file', label: 'File'}

  #Shop--------------------------------------------------------------------------------------------------------------------
      ShopCategorie:
        class: App\Entity\ShopCategorie
        list:
          sort: ['scatOrder', 'ASC']
          fields:
            - {property: 'scatOrder', label: 'Rangschikking'}
            - {property: 'scatNaam', label: 'Categorie Naam'}
        form:
          fields:
            - {property: 'scatOrder', label: 'Rangschikking'}
            - {property: 'scatNaam', label: 'Categorie Naam'}
            - {property: 'shopmaterialen', label: 'shop items'}

      Shopmateriaal:
        class: App\Entity\Shopmateriaal
        list:
          sort: ['smatOrder', 'ASC']
          fields:
            - {property: 'smatOrder', label: 'Rangschikking'}
            - {property: 'smatScat', label: 'Categorie'}
            - {property: 'smatNaam', label: 'materiaal Naam'}
            - {property: 'smatInStock', label: 'In Stock'}
            - {property: 'smatAfmeting', label: 'Afmetingen'}
            - {property: 'smatPrijs', label: 'Prijs'}
        form:
          fields:
            - {property: 'smatOrder', label: 'Rangschikking'}
            - {property: 'smatScat', label: 'Categorie'}
            - {property: 'smatNaam', label: 'materiaal Naam'}
            - {property: 'smatInStock', label: 'In Stock'}
            - {property: 'smatAfmeting', label: 'Afmetingen'}
            - {property: 'smatPrijs', label: 'Prijs', type: 'money', type_options: { currency: 'EUR' }}

#fabmoment==============================================================================================================================
      Fabmoment:
        class: App\Entity\Fabmoment
        list:
          sort: 'fabDatum'
          fields:
            - {property: 'fabIsPosted', label: 'Publiek'}
            - {property: 'fabDatum', label: 'Datum'}
            - {property: 'fabTitel', label: 'Titel'}
            - {property: 'fabOmschrijving', label: 'Omschrijving'}
        form:
          fields:
            - {property: 'fabIsPosted', label: 'Publiek'}
            - {property: 'fabDatum', label: 'Datum'}
            - {property: 'fabTitel', label: 'Titel'}
            - {property: 'fabOmschrijving', label: 'Omschrijving'}
            #TODO:-----
      FabImg:
        class: App\Entity\FabImg
        list:
          fields:
            - {property: 'fabimgFab', label: 'Fabmoment'}
            - {property: 'fabimgImgPad', label: 'Afbeelding'}
            - {property: 'fabimgImgAlt', label: 'Afbeelding Omschrijving'}
        form:
          fields:
            - {property: 'fabimgFab', label: 'Fabmoment'}
            - {property: 'fabimgImgPad', label: 'Afbeelding'}
            - {property: 'fabimgImgAlt', label: 'Afbeelding Omschrijving'}
      FabFile:
        class: App\Entity\FabFile
        list:
          fields:
            - {property: 'fabfileFab', label: 'Fabmoment'}
            - {property: 'fabfileOmschrijving', label: 'File omschrijving'}
            - {property: 'fabfilePad', label: 'File', type: 'file'}
        form:
          fields:
            - {property: 'fabfileFab', label: 'Fabmoment'}
            - {property: 'fabfileOmschrijving', label: 'File omschrijving'}
            - {property: 'fabfilePad', label: 'File', type: 'file'}
      Materiaal:
        class: App\Entity\Materiaal
        list:
          fields:
            - {property: 'matNaam', label: 'Materiaal'}
        form:
          fields:
            - {property: 'matNaam', label: 'Materiaal'}

#Nieuws & Events==============================================================================================================================
  #Nieuws--------------------------------------------------------------------------------------------------------------------
      Nieuws:
        class: App\Entity\Nieuws
#        list:
#          fields:
#        form:
#          fields:
  #Nieuws--------------------------------------------------------------------------------------------------------------------
      Event:
        class: App\Entity\Event
#        list:
#          fields:
#        form:
#          fields:
      Inschrijving:
        class: App\Entity\Inschrijving
#        list:
#          fields:
#        form:
#          fields:

#user==============================================================================================================================
      User:
        class: App\Entity\User
#        list:
#          fields:
#        form:
#          fields:
      MachineRecht:
        class: App\Entity\MachineRecht
#        list:
#          fields:
#        form:
#          fields:
      MachineLog:
        class: App\Entity\MachineLog
#        list:
#          fields:
#        form:
#          fields:
