vich_uploader:
    db_driver: orm

    mappings:
        machine_img:
            uri_prefix: '%uploads_machine_images_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_machine_images_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        machine_file:
            uri_prefix: '%uploads_machine_file_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_machine_file_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer