vich_uploader:
    db_driver: orm

    mappings:
        machine_img:
            uri_prefix: '%uploads_machine_images_path%'
            upload_destination: '%kernel.project_dir%/../%uploads_machine_images_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        machine_file:
            uri_prefix: '%uploads_machine_file_path%'
            upload_destination: '%kernel.project_dir%/../%uploads_machine_file_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        fab_img:
            uri_prefix: '%uploads_fab_img_path%'
            upload_destination: '%kernel.project_dir%/../%uploads_fab_img_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        eve_img:
            uri_prefix: '%uploads_eve_img_path%'
            upload_destination: '%kernel.project_dir%/../%uploads_eve_img_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

##local dvelopment
#    mappings:
#        machine_img:
#            uri_prefix: '%uploads_machine_images_path%'
#            upload_destination: '%kernel.project_dir%/public/%uploads_machine_images_path%'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#
#        machine_file:
#            uri_prefix: '%uploads_machine_file_path%'
#            upload_destination: '%kernel.project_dir%/public/%uploads_machine_file_path%'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#
#        fab_img:
#            uri_prefix: '%uploads_fab_img_path%'
#            upload_destination: '%kernel.project_dir%/public/%uploads_fab_img_path%'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#
#        eve_img:
#            uri_prefix: '%uploads_eve_img_path%'
#            upload_destination: '%kernel.project_dir%/public/%uploads_eve_img_path%'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer