vich_uploader:
    db_driver: orm

    mappings:
        machine_img:
            uri_prefix: '%uploads_machine_images_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_machine_images_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        machine_file:
            uri_prefix: '%uploads_machine_file_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_machine_file_path%'
